version: '3'

services:
  web:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    container_name: my-flask-app
    ports:
      - "5000:80"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
